[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings= ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/","@uniswap/v3-core/contracts/=lib/v3-core/contracts/"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config